[project]
name = "japan-trip-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.9",
    "requests>=2.32.5",
]
