# The URL the site will be built for
base_url = "https://japan2025.asermax.com"
title = "Japan Trip 2025"
description = ""
theme = "anatole-zola"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Enable tags and categories
taxonomies = [
    {name = "tags", feed = true},
    {name = "categories", feed = true},
    {name = "regions", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
# Trip-specific metadata
author = "Agus"
trip_year = 2025
trip_duration = "2-3 weeks"
trip_start_date = "2025-04-01"

# Google Maps API Configuration
# For local development: copy to config.local.toml and add your API key
# For GitHub Pages: Set GOOGLE_MAPS_API_KEY secret in repository settings
google_maps_api_key = "PLACEHOLDER_WILL_BE_REPLACED_BY_WORKFLOW"

# Anatole theme configuration
[extra.social]
github = ""
twitter = ""
instagram = ""
linkedin = ""

[extra.show]
tags = true
links = false

# Custom translations for our Japan trip
[translations]
language_name = "English"
about = "About This Trip"
home = "Timeline"
tags = "Tags"
archive = "All Places"
links = "Resources"
date_format = "%B %d"
next_page = "Next"
last_page = "Previous"
