name: Build and deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Generate timeline content
        run: uv run python scripts/generate_timeline.py --research research --output site/content

      - name: Install Zola
        run: sudo snap install --edge zola

      - name: Configure Google Maps API Key
        run: |
          sed -i 's/google_maps_api_key = ".*"/google_maps_api_key = "${{ secrets.GOOGLE_MAPS_API_KEY }}"/' site/config.toml

      - name: Build site
        run: cd site && zola build

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/public/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4